const express = require("express")
const products=require("./products")
const categories=require("./categories")
const banners=require("./banners")
const cart=require("./cart")
const auth=require("./auth")
const settings=require("./settings")
const manufacturer=require("./manufacturer")
const order=require("./order")
const region=require("./region")
const mail=require("./mail")
const charge=require("./charge")
const router = express.Router()

router.use("/products",products)
router.use("/categories",categories)
router.use("/banners",banners)
router.use("/cart",cart)
router.use("/auth",auth)
router.use("/settings",settings)
router.use("/manufacturer",manufacturer)
router.use("/order",order)
router.use("/region",region)
router.use("/mail",mail)
router.use("/charge",charge)
module.exports=router